language: python

python:
  - "3.4"
  - "3.6"

branches:
  only:
    - master

# command to install requirements
install:
  - pip install coveralls
  - pip install -r requirements/base.txt
  - python setup.py -q develop

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=bormeparser setup.py test

after_success:
  - coveralls
